server:
  port: 8080

database:
  postgres:
    host: "{POSTGRES_HOST}"
    port: "{POSTGRES_PORT}"
    username: "{POSTGRES_USER}"
    password: "{POSTGRES_PASSWORD}"
    name: "{POSTGRES_DB}"
  redis:
    host: "{POSTGRES_HOST}"
    port: "{POSTGRES_PORT}"
    username: "{POSTGRES_USER}"
    password: "{POSTGRES_PASSWORD}"
    name: "{POSTGRES_DB}"

security:
  jwt:
    jwt_secret: "{JWT_SECRET}"
    access_expires_in: 2h
    refresh_expires_in: 1d
  hash:
    secret: "{HASH_SECRET}"


providers:
  plum:
    active: true
    production: false
    host: https://checkout.paycom.uz
    merchant_id: 1
